# 配置文件版本
version: "3"


# 管理的服务
services:

    demo:
        build:
            context: .
            dockerfile: Dockerfile
        image: ${COMPOSE_IMAGE_NAME}:latest
        container_name: pf_demo
        hostname: pf_demo
        volumes:
            # 项目目录
            - ..:${COMPOSE_PROJECT_DIR}:ro
            # 项目日志目录
            - ${HOST_LOG_DIR}:${COMPOSE_LOG_DIR}:rw
            # crontab配置
            - ../configs/crontab_demo.ini:/var/spool/cron/root:ro
            # 日志轮转配置
            - ../configs/logrotate_demo:/etc/logrotate.d/logrotate_conf:ro
        working_dir: ${COMPOSE_PROJECT_DIR}/bin
        privileged: true
        command:
            - /bin/bash
            - -c
            - |
                /bin/bash run_demo.sh
                /usr/sbin/init
        logging:
            driver: json-file
            options:
                max-size: 100m
                max-file: "3"
        restart: always
        networks:
            - pf

    web:
        build:
            context: .
            dockerfile: Dockerfile
        image: ${COMPOSE_IMAGE_NAME}:latest
        container_name: pf_web
        hostname: pf_web
        volumes:
            # 项目目录
            - ..:${COMPOSE_PROJECT_DIR}:ro
            # 项目日志目录
            - ${HOST_LOG_DIR}:${COMPOSE_LOG_DIR}:rw
        working_dir: ${COMPOSE_PROJECT_DIR}/bin
        privileged: true
        # environment:
        #     - COMPOSE_PROJECT_DIR=${COMPOSE_PROJECT_DIR}
        ports:
            - ${HOST_WEB_PORT}:8000/tcp
        command:
            - /bin/bash
            - -c
            - |
                /bin/bash run_web.sh
                /usr/sbin/init
        logging:
            driver: json-file
            options:
                max-size: 100m
                max-file: "3"
        restart: always
        networks:
            - pf

    nginx:
        image: nginx:latest
        container_name: pf_nginx
        hostname: pf_nginx
        volumes:
            - ${HOST_LOG_DIR}/nginx:/var/log/nginx:rw
            - ${HOST_NGINX_DIR}/conf.d:/etc/nginx/conf.d:rw
            - ${HOST_NGINX_DIR}/www:/var/www:ro
        ports:
            - ${HOST_NGINX_HTTP_PORT:-80}:80/tcp
            - ${HOST_NGINX_HTTPS_PORT:-443}:443/tcp
        logging:
            driver: json-file
            options:
                max-size: 100m
                max-file: "3"
        restart: always
        depends_on:
            - web
        networks:
            - pf

networks:
    pf:
        ipam:
            driver: default
