# 配置文件版本
version: "3"


# 管理的服务
services:

    demo:
        build:
            context: .
            dockerfile: Dockerfile
        image: ${COMPOSE_IMAGE_NAME}:latest
        hostname: pf_demo
        volumes:
            # 项目目录
            - ..:/projects/py_framework:ro
            # 项目日志目录
            - ${HOST_LOG_DIR}/demo:/var/log/demo:rw
            # crontab配置
            - ../configs/crontab_demo.ini:/var/spool/cron/root:ro
        working_dir: /projects/py_framework/bin
        privileged: true
        command:
            - /bin/bash
            - -c
            - |
                /bin/bash run_demo.sh
                /usr/sbin/init
        logging:
            driver: json-file
            options:
                max-size: 100m
                max-file: "3"
        restart: always
        networks:
            - pf

    web:
        build:
            context: .
            dockerfile: Dockerfile
        image: ${COMPOSE_IMAGE_NAME}:latest
        hostname: pf_web
        volumes:
            # 项目目录
            - ..:/projects/py_framework:ro
            # 项目日志目录
            - ${HOST_LOG_DIR}/web:/var/log/web:rw
        working_dir: /projects/py_framework/bin
        privileged: true
        ports:
            - ${HOST_WEB_PORT}:8000/tcp
        command:
            - /bin/bash
            - -c
            - |
                /bin/bash run_web.sh
                /usr/sbin/init
        logging:
            driver: json-file
            options:
                max-size: 100m
                max-file: "3"
        restart: always
        networks:
            - pf

    nginx:
        image: nginx:latest
        hostname: pf_nginx
        volumes:
            - ${HOST_LOG_DIR}/nginx:/var/log/nginx:rw
            - ${HOST_NGINX_DIR}/conf.d:/etc/nginx/conf.d:rw
            - ${HOST_NGINX_DIR}/nginx.conf:/etc/nginx/nginx.conf:ro
            - ${HOST_NGINX_DIR}/ssl:/etc/nginx/ssl:ro
            - ${HOST_NGINX_DIR}/www:/var/www:ro
        ports:
            - ${HOST_NGINX_HTTP_PORT:-80}:80/tcp
            - ${HOST_NGINX_HTTPS_PORT:-443}:443/tcp
        privileged: true
        logging:
            driver: json-file
            options:
                max-size: 100m
                max-file: "3"
        restart: always
        depends_on:
            - web
        networks:
            - pf

    logrotate:
        build:
            context: .
            dockerfile: Dockerfile
        image: ${COMPOSE_IMAGE_NAME}:latest
        hostname: pf_logrotate
        volumes:
            # 日志目录
            - ${HOST_LOG_DIR}:/logs:rw
            # demo服务日志轮转配置
            - ../configs/logrotate_demo:/etc/logrotate.d/domo:ro
            # nginx服务日志轮转配置
            - ../configs/logrotate_demo:/etc/logrotate.d/nginx:ro
        working_dir: /logs
        privileged: true
        command:
            - /bin/bash
            - -c
            - |
                /usr/sbin/init
        logging:
            driver: json-file
            options:
                max-size: 100m
                max-file: "3"
        restart: always
        networks:
            - pf

networks:
    pf:
        ipam:
            driver: default
