# 配置文件版本
version: "3"


# 管理的服务
services:

    demo:
        build:
            context: .
            dockerfile: Dockerfile
        image: ${COMPOSE_IMAGE_NAME}:latest
        container_name: demo
        hostname: demo
        volumes:
            # 项目目录
            - ..:${COMPOSE_PROJECT_DIR}:ro
            # 项目日志目录
            - ${HOST_LOG_DIR}:${COMPOSE_LOG_DIR}:rw
            # crontab配置
            - ../configs/crontab.ini:/var/spool/cron/root:ro
            # 日志轮转配置
            - ../configs/logrotate_conf:/etc/logrotate.d/logrotate_conf:ro
            # 项目部署目录 容器内使用sed命令修改.env时需要可写权限创建临时文件
            - .:${COMPOSE_PROJECT_DIR}/deploy:rw
        working_dir: ${COMPOSE_PROJECT_DIR}/bin
        privileged: true
        command:
            - /bin/bash
            - -c
            - |
                /bin/bash run.sh &
                /usr/sbin/init
        logging:
            driver: json-file
            options:
                max-size: 200m
                max-file: "3"
        restart: always
        networks:
            - py3


networks:
    py3:
        ipam:
            driver: default
